---
version: '3'

services:
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
  activerecord:
    image: activerecord:latest
    environment:
      - ARCONN=mysql2
      - MYSQL_HOST=mysql-db
    depends_on:
      - mysql-db
